Update check-version.yaml

diff --git a/.github/workflows/check-version.yaml b/.github/workflows/check-version.yaml
--- a/.github/workflows/check-version.yaml
+++ b/.github/workflows/check-version.yaml
@@ -15,9 +15,9 @@ jobs:
       - name: Check if version file is updated
         id: check-updated
         run: |
-          VERSION_FILE=version.txt
-          CHANGES=$(git diff --name-only HEAD~1 $VERSION_FILE)
-          if [ -z "$CHANGES" ]; then
+          VERSION_FILE=path/to/version/file.txt
+          CHANGES=$(git ls-files --error-unmatch "$VERSION_FILE" || echo "not found")
+          if [ "$CHANGES" == "not found" ]; then
             echo "::set-output name=updated::false"
           else
             echo "::set-output name=updated::true"
